# Generated by Django 3.2.9 on 2021-11-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211124_0112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tessiu',
            name='inflamation',
        ),
        migrations.AddField(
            model_name='tessiu',
            name='inflammation',
            field=models.FloatField(default=0, verbose_name='Inflamacion'),
            preserve_default=False,
        ),
    ]
